### ISSUE TITLE
O terminal não esta vindo com o pacman, os arquivos estão corrompendo com facilidade, são eles: Root, imagem iso e um outro la, mas esta bem otimizado, poderia colocar mais opções de configuração, ainda esta meio cru e da para colocar para aceitar instalar arquivos .deb ou .mbr para ajudar pessoas que são novas no sistema!

### ISSUE THREAD

**Issue by Jvtopsilva090** [Blade-OS/os#3]

**Comment by novusthedev** [comment]
**Saudações, o Blade OS permite que você instale Flatpaks junto com pacotes Debian regulares, incluindo arquivos deb. No entanto, o Pacman não está incluído porque não é oficialmente suportado em sistemas baseados em Debian. A corrupção de arquivo pode ser devido a um erro ao instalar o sistema em mídia inicializável e/ou unidade(s) do sistema.**

Obrigado por fornecer feedback sobre o Blade OS! Ele ajuda no desenvolvimento da próxima versão e nos permite fazer alterações e adicionar novos recursos ao sistema.

_De,
Novus (Criador do Blade OS)_
